"""Add updated_at to messages

Revision ID: 2c0c33bc3e3a
Revises: 2c86421d0843
Create Date: 2025-09-10 13:06:25.713503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0c33bc3e3a'
down_revision = '2c86421d0843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
